name: base
channels:
  - conda-forge
dependencies:
  - pip
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - pillow
  - opencv
  - tqdm
  - pyyaml
  - psutil
  - requests
  - pip:
      - albumentations==1.4.7
      - scikit-image==0.21.0
      - timm==1.0.3
      - transformers==4.41.1
      - tokenizers==0.19.1
      - huggingface-hub==0.23.1
      - safetensors==0.4.3
      - pytorch-tabnet==4.1.0
      - pydicom==2.4.4
      - shapely==2.0.4
      - imageio==2.34.1
      - omegaconf==2.3.0
      - imgaug==0.4.0
      - dicomsdl==0.109.3
      - tensorboard==2.14.0
