name: env
channels:
  - conda-forge
  - nodefaults
dependencies:
  - unicodedata2==15.1.0=py38h5eee18b_0
  - gstreamer==1.14.1=h5eee18b_1
  - libnpp==11.8.0.86=0
  - stack_data==0.2.0=pyhd3eb1b0_0
  - blas==1.0=mkl
  - mpc==1.1.0=h10f8cd9_1
  - libgomp==11.2.0=h1234567_1
  - pytorch==2.2.2=py3.8_cuda11.8_cudnn8.7.0_0
  - nettle==3.7.3=hbbd107a_1
  - fonttools==4.51.0=py38h5eee18b_0
  - libpng==1.6.37=h21135ba_2
  - _libgcc_mutex==0.1=main
  - tornado==6.3.3=py38h5eee18b_0
  - asttokens==2.0.5=pyhd3eb1b0_0
  - pip==24.0=py38h06a4308_0
  - libcusparse==11.7.5.86=0
  - giflib==5.2.1=h5eee18b_3
  - zstd==1.5.0=ha95c52a_0
  - libbrotlidec==1.0.9=h5eee18b_8
  - charset-normalizer==2.0.4=pyhd3eb1b0_0
  - pysocks==1.7.1=py38h06a4308_0
  - requests==2.31.0=py38h06a4308_1
  - zipp==3.17.0=py38h06a4308_0
  - wheel==0.43.0=py38h06a4308_0
  - libbrotlicommon==1.0.9=h5eee18b_8
  - ptyprocess==0.7.0=pyhd3eb1b0_2
  - sympy==1.12=py38h06a4308_0
  - readline==8.2=h5eee18b_0
  - xz==5.4.6=h5eee18b_1
  - cuda-cudart==11.8.89=0
  - pyyaml==6.0.1=py38h5eee18b_0
  - markupsafe==2.1.3=py38h5eee18b_0
  - mkl_fft==1.3.8=py38h5eee18b_0
  - libstdcxx-ng==11.2.0=h1234567_1
  - brotli-bin==1.0.9=h5eee18b_8
  - mkl==2023.1.0=h213fc3f_46344
  - mpfr==4.0.2=hb69a4c5_1
  - bzip2==1.0.8=h5eee18b_6
  - libcublas==11.11.3.6=0
  - libglib==2.78.4=hdc74915_0
  - glib==2.78.4=h6a678d5_0
  - expat==2.4.8=h27087fc_0
  - python==3.8.18=h7a1cb2a_0
  - libbrotlienc==1.0.9=h5eee18b_8
  - pyqt==5.9.2=py38h05f1152_4
  - dbus==1.13.18=hb2f20db_0
  - gdcm==2.8.9=py38heca6765_3
  - setuptools==69.5.1=py38h06a4308_0
  - typing_extensions==4.11.0=py38h06a4308_0
  - fontconfig==2.14.1=hef1e5e3_0
  - libcusolver==11.4.1.48=0
  - libiconv==1.16=h5eee18b_3
  - lame==3.100=h7b6447c_0
  - openjpeg==2.4.0=hb52868f_1
  - pillow==9.4.0=py38h6a678d5_0
  - gmp==6.2.1=h295c915_3
  - idna==3.7=py38h06a4308_0
  - torchtriton==2.2.0=py38
  - libunistring==0.9.10=h27cfd23_0
  - libwebp-base==1.2.2=h7f98852_1
  - gst-plugins-base==1.14.1=h6a678d5_1
  - zlib==1.2.13=h5eee18b_1
  - networkx==3.1=py38h06a4308_0
  - pyparsing==3.0.9=py38h06a4308_0
  - libcufile==1.9.1.3=0
  - openssl==1.1.1w=h7f8727e_0
  - openh264==2.1.1=h4ff587b_0
  - icu==58.2=he6710b0_3
  - pytorch-mutex==1.0=cuda
  - lcms2==2.12=h3be6417_0
  - six==1.16.0=pyhd3eb1b0_1
  - backcall==0.2.0=pyhd3eb1b0_0
  - tbb==2021.8.0=hdb19cb5_0
  - _openmp_mutex==5.1=1_gnu
  - filelock==3.13.1=py38h06a4308_0
  - intel-openmp==2023.1.0=hdb19cb5_46306
  - libffi==3.4.4=h6a678d5_1
  - qt==5.9.7=h5867ecd_1
  - gnutls==3.6.15=he1e5248_0
  - prompt-toolkit==3.0.43=py38h06a4308_0
  - cuda-libraries==11.8.0=0
  - brotli==1.0.9=h5eee18b_8
  - jedi==0.18.1=py38h06a4308_1
  - jinja2==3.1.3=py38h06a4308_0
  - cuda-nvrtc==11.8.89=0
  - pcre2==10.42=hebb0a14_1
  - pytorch-cuda==11.8=h7e8668a_5
  - brotli-python==1.0.9=py38h6a678d5_8
  - python-dateutil==2.9.0post0=py38h06a4308_2
  - ld_impl_linux-64==2.38=h1181459_1
  - llvm-openmp==14.0.6=h9e868ea_0
  - libxcb==1.15=h7f8727e_0
  - python_abi==3.8=2_cp38
  - urllib3==2.2.1=py38h06a4308_0
  - libcurand==10.3.5.147=0
  - ipython==8.12.2=py38h06a4308_0
  - freetype==2.12.1=h4a9f257_0
  - matplotlib-inline==0.1.6=py38h06a4308_0
  - libjpeg-turbo==2.1.1=h7f98852_0
  - matplotlib==3.7.2=py38h06a4308_0
  - matplotlib-base==3.7.2=py38h1128e8f_0
  - json-c==0.15=h98cffda_0
  - cycler==0.11.0=pyhd3eb1b0_0
  - gmpy2==2.1.2=py38heeb90bb_0
  - mpmath==1.3.0=py38h06a4308_0
  - yaml==0.2.5=h7b6447c_0
  - tk==8.6.14=h39e8969_0
  - wcwidth==0.2.5=pyhd3eb1b0_0
  - decorator==5.1.1=pyhd3eb1b0_0
  - glib-tools==2.78.4=h6a678d5_0
  - libcufft==10.9.0.58=0
  - parso==0.8.3=pyhd3eb1b0_0
  - pexpect==4.8.0=pyhd3eb1b0_3
  - joblib==1.4.0=py38h06a4308_0
  - sip==4.19.13=py38h295c915_0
  - contourpy==1.0.5=py38hdb19cb5_0
  - libwebp==1.2.2=h55f646e_0
  - torchaudio==2.2.2=py38_cu118
  - libidn2==2.3.4=h5eee18b_0
  - mkl-service==2.4.0=py38h5eee18b_1
  - pure_eval==0.2.2=pyhd3eb1b0_0
  - lz4-c==1.9.3=h9c3ff4c_1
  - libtasn1==4.19.0=h5eee18b_0
  - libxml2==2.9.14=h74e7548_0
  - pickleshare==0.7.5=pyhd3eb1b0_1003
  - torchvision==0.17.2=py38_cu118
  - ffmpeg==4.3=hf484d3e_0
  - cuda-cupti==11.8.87=0
  - jpeg==9e=h166bdaf_1
  - libnvjpeg==11.9.0.86=0
  - ncurses==6.4=h6a678d5_0
  - cuda-runtime==11.8.0=0
  - traitlets==5.7.1=py38h06a4308_0
  - cuda-nvtx==11.8.86=0
  - executing==0.8.3=pyhd3eb1b0_0
  - certifi==2024.2.2=py38h06a4308_0
  - importlib_resources==6.1.1=py38h06a4308_1
  - libgcc-ng==11.2.0=h1234567_1
  - libtiff==4.2.0=hf544144_3
  - mkl_random==1.2.4=py38hdb19cb5_0
  - pygments==2.15.1=py38h06a4308_1
  - sqlite==3.45.3=h5eee18b_0
  - ca-certificates==2024.3.11=h06a4308_0
  - kiwisolver==1.4.4=py38h6a678d5_0
